/**
 * Embed assets-gen/* into src/client/art.generated.ts as data URIs so the
 * client bundle activates without any temp files or remote URLs.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { resolve, dirname, extname } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const ASSETS = [
  ['WK_COVER', 'cover.webp'],
  ['WK_ICON', 'icon.png'],
  ['WK_POSE_DIALOGUE', 'pose-dialogue.webp'],
  ['WK_POSE_CHOICE', 'pose-choice.webp'],
  ['WK_POSE_EXECUTION', 'pose-execution.webp'],
  ['WK_POSE_RECOVERY', 'pose-recovery.webp'],
  ['WK_POSE_CLEAR', 'pose-clear.webp'],
  ['WK_BG_DIALOGUE', 'bg-dialogue.webp'],
  ['WK_BG_EXECUTION', 'bg-execution.webp'],
  ['WK_TUDIMIAO', 'tudimiao.webp'],
]

const MIME = { '.webp': 'image/webp', '.png': 'image/png' }

let out = '/** Generated by tools/embed-assets.mjs — do not edit by hand. */\n'
for (const [name, file] of ASSETS) {
  const data = await readFile(resolve(root, 'assets-gen', file))
  const mime = MIME[extname(file)]
  out += `export const ${name} = 'data:${mime};base64,${data.toString('base64')}'\n`
}

await writeFile(resolve(root, 'src/client/art.generated.ts'), out)
console.log(`embedded ${ASSETS.length} assets`)
